### ISSUE TITLE
支持通过huggingface + lora加载llama系列模型

### ISSUE THREAD

**Issue by Ricardokevins** [hkust-nlp/ceval#19]
你好
现有的基于llama的架构测试使用的是meta官方的仓库代码，请问会支持huggingface加载模型的测试方法吗，特别是加载huggingface+lora的结果，对于测试和对比指令微调过后系列的模型能力会方便一些

**Comment by jxhe** [comment]
我们正在将ceval集成到 [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) 中，届时应该可以参考lm-evaluation-harness来测试hf中的模型，敬请期待

**Comment by jxhe** [comment]
https://github.com/hkust-nlp/ceval#use-through-evaluation-harness
