### ISSUE TITLE
建议支持`--subject=all`和`--subject=hard`

### ISSUE THREAD

**Issue by wjfwzzc** [hkust-nlp/ceval#4]
如题，现在不仅测起来很麻烦，而且不好根据大类汇总。
在`eval.py`里根据`subject_mapping.json`应该就能支持？

btw，想问下leader board中大类的平均分是怎么算出来的，是按题目数平均还是按类别平均？（MMLU好像是按题目数平均的）

**Comment by linghongli** [comment]
+1

**Comment by linghongli** [comment]
自己手动实现了一版

**Comment by jxhe** [comment]
seems somebody has uploaded "all" version: https://huggingface.co/datasets/liyucheng/ceval_all
