### ISSUE TITLE
自然语言处理的相关任务属于知识型还是推理型任务呢？

### ISSUE THREAD

**Issue by liumingzhu6060** [hkust-nlp/ceval#59]
你好，请教一下，自然语言处理的相关任务，比如机器翻译、语义相似性判断，应该属于知识型还是推理性任务呢，还是两者都不属于，现有的测试集是否应该增加这部分的测试？

**Comment by jxhe** [comment]
机器翻译感觉知识和推理成分都有，语义相似性或者NLI等任务更接近纯推理性任务。CEval目前的版本只关注中文知识测试
