### ISSUE TITLE
Fail to send verification code. Please try again

### ISSUE THREAD

**Issue by Abigail61** [hkust-nlp/ceval#71]
在官网中提交测试集结果需要用户登录，但新用户注册账号失败，官网无法发送邮箱验证码

**Comment by zzh068** [comment]
Sorry about this, now is working

**Comment by zzh068** [comment]
> 在官网中提交测试集结果需要用户登录，但新用户注册账号失败，官网无法发送邮箱验证码

Sorry about this, now is working

**Comment by Abigail61** [comment]
Thank you. I successfully registered an account, but an error occurred on the submit page and I could not submit the data. I've tried it many times and it's still like this：






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hkust-nlp/ceval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月10日(星期天) 下午3:52
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hkust-nlp/ceval] Fail to send verification code. Please try again (Issue #71)





 
Sorry about this, now is working

**Comment by zzh068** [comment]
> Thank you. I successfully registered an account, but an error occurred on the submit page and I could not submit the data. I've tried it many times and it's still like this：
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hkust-nlp/ceval" ***@***.***&gt;; 发送时间:&nbsp;2023年12月10日(星期天) 下午3:52 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hkust-nlp/ceval] Fail to send verification code. Please try again (Issue #71) Sorry about this, now is working — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

it's fixed now~
