### ISSUE TITLE
Failed to send verification code. Please try again.

### ISSUE THREAD

**Issue by Lukikay** [hkust-nlp/ceval#73]
在官网注册新账户，邮箱验证码发送失败，无法正常注册新账户了：```Failed to send verification code. Please try again.```
请帮忙看一下

**Comment by zzh068** [comment]
Due to some limitations with Google Mail, we've now switched to Outlook. Please give it another try (might be a slight delay in receiving emails, so please be patient).

**Comment by Lukikay** [comment]
Thanks for helping! It's working now.
