### ISSUE TITLE
HOW TO EVALUATE STEM???

### ISSUE THREAD

**Issue by AkKari808** [hkust-nlp/ceval#74]
I found that I could only assess each small subject, such as computer_network, instead of a large subject, such as STEM. Is it true that in the experiment you can only measure each minor subject and then average the final score to get an average score for a major subject?

我发现在测评的时候只能测评每个小课目，比如computer_network，而不是一个大课目比如STEM。实际在实验中只能对每个小科目进行测评然后最后算平均分得到一个大科目的平均分吗？

**Comment by HYZ17** [comment]
对的
