### ISSUE TITLE
The leaderboard in GitHub is out of sync with the latest version on the official website

### ISSUE THREAD

**Issue by zhimin-z** [hkust-nlp/ceval#76]
![image](https://github.com/hkust-nlp/ceval/assets/8592144/4546b262-5b12-4c67-b5b0-f44f83b642d9)
![image](https://github.com/hkust-nlp/ceval/assets/8592144/ac8aff0f-3f9e-4986-aa3e-adb7cbd38834)

**Comment by HYZ17** [comment]
The leaderboard in GitHub only retains the evaluation results in our paper. For latest results, please visit our official website.
