### ISSUE TITLE
Failed to send verification code. Please try again.

### ISSUE THREAD

**Issue by Wumengyao** [hkust-nlp/ceval#78]
![image](https://github.com/hkust-nlp/ceval/assets/16360262/b554353f-9aa5-493c-931d-a5b394c1a406)

在官网注册新账户，邮箱验证码发送失败，无法正常注册新账户了：Failed to send verification code. Please try again.
尝试了QQ邮箱、outlook、gmail均失败。请帮忙看一下。

**Comment by HYZ17** [comment]
刚刚尝试了一下可以正常收到注册验证码，谢谢

**Comment by Cherryjingyao** [comment]
今天刚试，同样的问题，Failed to send verification code. Please try again.QQ邮箱、outlook、gmail均失败

**Comment by jxhe** [comment]
Should be resolved now @Cherryjingyao

**Comment by Krueske** [comment]
昨天和今天尝试注册的时候也碰到了相同的问题，Failed to send verification code. Please try again.

**Comment by gqjia** [comment]
Failed to send verification code. Please try again. 
这边也遇到同样的问题 试了 qq gmail 163

**Comment by HYZ17** [comment]
应该已经解决了，请重新尝试，谢谢

**Comment by Amygu1994** [comment]
今天注册遇到同样的问题，Failed to send verification code. Please try again.  现在还可以开放注册吗？

**Comment by HYZ17** [comment]
> 今天注册遇到同样的问题，Failed to send verification code. Please try again. 现在还可以开放注册吗？
已经解决，请重新尝试，谢谢

**Comment by WLS2002** [comment]
今天在尝试找回密码和注册时遇到了同样的问题：Sending failed. Please try it later or contact us for help

**Comment by HYZ17** [comment]
> 今天在尝试找回密码和注册时遇到了同样的问题：Sending failed. Please try it later or contact us for help

已经解决，请重新尝试，谢谢

**Comment by shiquan-wang** [comment]
今天在找回密码注册账号时遇到了同样的问题：Failed to send verification code. Please try again.

**Comment by HYZ17** [comment]
> 今天在找回密码注册账号时遇到了同样的问题：Failed to send verification code. Please try again.

已经解决，请重新尝试，谢谢

**Comment by colinzhaoxp** [comment]
今天注册遇到了无法发送验证码错误

**Comment by HYZ17** [comment]
> 今天注册遇到了无法发送验证码错误

已经解决，请重新尝试，谢谢

**Comment by colinzhaoxp** [comment]
> > 今天注册遇到了无法发送验证码错误
> 
> 已经解决，请重新尝试，谢谢

感谢回复，但是刚才尝试注册，还是失败

**Comment by liangrui** [comment]
有解决吗？现在注册也出现这个问题。

**Comment by HYZ17** [comment]
> 有解决吗？现在注册也出现这个问题。

已经解决，请重新尝试，谢谢

**Comment by HYZ17** [comment]
> > > 今天注册遇到了无法发送验证码错误
> > 
> > 
> > 已经解决，请重新尝试，谢谢
> 
> 感谢回复，但是刚才尝试注册，还是失败

已经解决，请重新尝试，谢谢
