### ISSUE TITLE
测试结果提交报错，点击process时，提示：Any subject must contain at least 50 questions to be calculated

### ISSUE THREAD

**Issue by hailing2024** [hkust-nlp/ceval#79]
把从官网下载的sample直接提交也是报这个错，是每个科目最少需要50条数据吗？
奇怪的是，把数据加到了每个科目50条数据，有时候报错，有时候能成功
然后，让别的小伙伴试了下，提交sample没有报错

**Comment by HYZ17** [comment]
我们设置的是至少提交50条数据
