### ISSUE TITLE
上传模型评测结果到网页上报错 Any subject must contain at least 50 questions to be calculated

### ISSUE THREAD

**Issue by mmarzl17** [hkust-nlp/ceval#85]
按这个格式准备的数据
<img width="584" alt="image" src="https://github.com/user-attachments/assets/5adbdecb-0c5b-4755-a520-2bbf8cdfcf8d">

**Comment by HYZ17** [comment]
你好，每个科目，至少需要保证有50道题目的答案才可以正常评测。
